name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: decompil3d
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target vinetracker \
            --image "image-{arch}-homeassistant-addon-vinetracker" \
            --docker-hub decompil3d
